// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd3Mlr-8z5RzcAQZ9Fs7hTuXoucZmZ4OU',
    appId: '1:130340918539:web:6fd308c9a1f3c046453e0e',
    messagingSenderId: '130340918539',
    projectId: 'phuc-61136382-flutter',
    authDomain: 'phuc-61136382-flutter.firebaseapp.com',
    storageBucket: 'phuc-61136382-flutter.appspot.com',
    measurementId: 'G-GGBE1BTDZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHrK6dHq1kFIRviFUBsN86DFlXQZ6F4k',
    appId: '1:130340918539:android:7b102176740401cc453e0e',
    messagingSenderId: '130340918539',
    projectId: 'phuc-61136382-flutter',
    storageBucket: 'phuc-61136382-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxqdB9klgpjO5A0u9_NF2S5SKPH69Q7Sc',
    appId: '1:130340918539:ios:9eb9272ecb0a1e3a453e0e',
    messagingSenderId: '130340918539',
    projectId: 'phuc-61136382-flutter',
    storageBucket: 'phuc-61136382-flutter.appspot.com',
    androidClientId: '130340918539-orst1krhcvesrqnbvqt0kj1daio9ik3a.apps.googleusercontent.com',
    iosClientId: '130340918539-642asag7d4asju1v0edjuf3vd15bom20.apps.googleusercontent.com',
    iosBundleId: 'com.example.phuc61cntt1',
  );
}
